provider: db


# ldap:
#   bind_dn: 'example_bind_dn'
#   bind_password: cGFzc3dvcmQ= # base64 encoded # echo -n 'password' | base64
#   encryption: 'simple_tls'
#   hostnames:
#     - 'example_hostname'
#     - 'example_hostname2'
#   basename: 'ou=users,dc=acme'
#   portnumber: 636
